#! /usr/bin/env ruby
#
require 'orocos'
require 'optparse'
Orocos.initialize

gui = false
optparse = OptionParser.new do |opt|
    opt.banner = "run [--gui] DEVICE"
    opt.on '--gui', "starts the Rock task inspection widget on the running task" do
        gui = true
    end
end
io_port = *optparse.parse(ARGV)
if !io_port
    puts optparse
    exit 1
end

if gui
    require 'vizkit'
end

Orocos.run 'ucm_schilling::Task' => 'ucm' do
#Orocos.run 'ctd_seabird_test' do
    Orocos.logger.level = Logger::DEBUG
    Orocos.log_all
    puts "deployed the ucm_schilling::Task task"

    ucm = Orocos::TaskContext.get 'ucm'
    ucm.io_port = io_port
    ucm.io_read_timeout = Time.at(2);
    ucm.config do |p|
        p.count0 = 1000;
	p.count50 = 2000;
	p.count100 = 3000;
    end
    ucm.configure
    ucm.start

    if gui
        task_inspector = Vizkit.default_loader.task_inspector
        task_inspector.config(ucm)
        task_inspector.show
        Vizkit.exec
    else
#        reader = ctd.ctd_samples.reader
#        Orocos.watch(ctd) do
#            if sample = reader.read
#                pp sample
#            end
#        end
    end
end

